apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: puebwqt30-nodejs 
  janus-idp.io/tekton: puebwqt30-nodejs
  backstage.io/kubernetes-id: puebwqt30-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: puebwqt30-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  